### ISSUE TITLE
这一句好像有问题，

### ISSUE THREAD

**Issue by xiaoxue508** [281677160/Custom#1]
find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
find package/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}
}

处理bypass的这一句有问题，路径不对，

**Comment by 281677160** [comment]
对不对也就这样了，作者那里抄来的，编译也能成功

**Comment by xiaoxue508** [comment]
find package/danshui/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
find package/danshui/*/ feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}

加上你的路径就好啦，不加提示bypass缺少依赖。

**Comment by 281677160** [comment]
啥意思？我编译也没提升缺依赖啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/Custom"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 下午2:05
收件人:&nbsp;"281677160/Custom"<Custom@noreply.github.com&gt;;
抄送:&nbsp;"DanShui"<281677160@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [281677160/Custom] 这一句好像有问题， (#1)





 
find package/danshui// feeds// -maxdepth 2 -path "luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-redir/shadowsocksr-libev-alt/g' {}
 find package/danshui// feeds/*/ -maxdepth 2 -path "*luci-app-bypass/Makefile" | xargs -i sed -i 's/shadowsocksr-libev-ssr-server/shadowsocksr-libev-server/g' {}
 
加上你的路径就好啦，不加提示bypass缺少依赖。

**Comment by xiaoxue508** [comment]
执行到 这一步的时候 ./scripts/feeds update -a && ./scripts/feeds install -a 
会有下面两个警告

WARNING: Makefile 'package/danshui/luci-app-bypass/Makefile' has a dependency on 'shadowsocksr-libev-ssr-redir', which does not exist
WARNING: Makefile 'package/danshui/luci-app-bypass/Makefile' has a dependency on 'shadowsocksr-libev-ssr-server', which does not exist
