### ISSUE TITLE
lede-x86-64 自动升级失败

### ISSUE THREAD

**Issue by tossp** [281677160/Custom#2]
# 测试信息

确实是正常的镜像

```
root@OpenWrt-nas:~# sysupgrade -T /tmp/Downloads/coolsnowwolf-lede-x86-64-202103171647-Legacy.img.gz
Image metadata not found
Reading partition table from bootdisk...
Reading partition table from image...
```

# 报错信息

```
root@OpenWrt-nas:~# /bin/AutoUpdate.sh
Openwrt-AutoUpdate Script V5.2

[03:42:59] 执行: 保留配置更新固件[静默模式]

[03:43:04] 梯子翻墙失败,可能导致固件下载速度缓慢!

[03:43:04] 正在检查版本更新...

[03:43:05] 正在获取云端固件版本...

固件作者: tossp
设备名称: x86-64
固件格式: Legacy.img.gz

当前固件版本: lede-x86-64-202103171647-Legacy
云端固件版本: lede-x86-64-202103171647-Legacy

云端固件名称: coolsnowwolf-lede-x86-64-202103171647-Legacy.img.gz
固件下载地址: https://github.com/tossp/build-openwrt/releases/download/update_Firmware
固件保存位置: /tmp/Downloads

[03:43:05] 正在删除旧版本固件...

[03:43:05] 正在下载固件,请耐心等待...

[03:43:12] 固件下载成功!

[03:43:12] 正在获取云端固件MD5,请耐心等待...

本地固件MD5:140c31cd86d41250a70ca51e71568f61
云端固件MD5:140c31cd86d41250a70ca51e71568f61

[03:43:14] MD5 对比成功!

[03:43:14] 检测到固件为 [.gz] 压缩格式,开始解压固件...

[03:43:15] 固件解压失败!
```

# 其他

建议同时做sha256对比

```shell
GET_SHA256=$(awk -F '[ :]' '/SHA256/ {print $2;exit}' ${Firmware_Detail})
CURRENT_SHA256=$(sha256sum ${Firmware} | cut -d ' ' -f1)
echo -e "\n本地固件SHA256:${CURRENT_MD5}"
echo "云端固件SHA256:${GET_SHA256}"
if [[ -z "${GET_SHA256}" ]] || [[ -z "${CURRENT_SHA256}" ]];then
        TIME && echo -e "SHA256 获取失败!"
        exit
fi
if [[ ! "${GET_SHA256}" == "${CURRENT_SHA256}" ]];then
        TIME && echo -e "SHA256 对比失败,请检查网络后重试!"
        exit
else
        TIME && echo -e "SHA256 对比成功!"
fi
```

**Comment by tossp** [comment]
@281677160 `AutoUpdate Script`版本是V5.2呀，要升级5.3才行？

**Comment by 281677160** [comment]
什么样的失败？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/Custom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午3:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/Custom] lede-x86-64 自动升级失败 (#2)





 
@281677160 AutoUpdate Script版本是V5.2呀，要升级5.3才行？

**Comment by tossp** [comment]
@281677160 

```
[03:43:14] 检测到固件为 [.gz] 压缩格式,开始解压固件...

[03:43:15] 固件解压失败!
```

**Comment by 281677160** [comment]
没安装压缩插件的程序？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "281677160/Custom"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 下午3:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [281677160/Custom] lede-x86-64 自动升级失败 (#2)





 
@281677160
 [03:43:14] 检测到固件为 [.gz] 压缩格式,开始解压固件... [03:43:15] 固件解压失败!

**Comment by tossp** [comment]
@281677160 这个版本打包出来gz就是有问题，我本地试了解压确实会报错，但是直接喂给`sysupgrade` 可以正常使用

**Comment by 281677160** [comment]
我刚编译的也是5.2的，再说压缩是源码的问题，不是定时更新插件做的，你编译出来有问题那就是源码问题了，我刚测试了刚刚编译出来的，没发现问题，你这里升级都少了安装解压程序的步骤，你用WinSCP工具连接路由器，然后找bin文件夹，里面的AutoUpdate.sh内容替换成我最新的AutoUpdate.sh内容，然后再执行命令看看吧

**Comment by tossp** [comment]
好的，谢谢
